server:
  port: "3000"

telegrambot:
  userName: "@TemplateSimpleBot"
  botToken: "5558689984:AAHktTbnkTXsBAdPX59CuBeqYC1gkmUC2pE"
  payToken: "284685063:TEST:NmI3ZTdkMjhhZGFk"
  webHookPath: "https://templatebotw.herokuapp.com/"

subscriptions:
  processPeriod: "1800000"
ping task:
  url: "https://www.google.com"
  period: "1200000"
